use contato;

CREATE TABLE `contacts` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL DEFAULT '',
	`email` VARCHAR(255) NOT NULL DEFAULT '',
	`telefone` VARCHAR(255) NOT NULL DEFAULT '',
	`message` TEXT NOT NULL DEFAULT '',
	`file` VARCHAR(255) NOT NULL DEFAULT '',
	`ip` VARCHAR(15) NOT NULL DEFAULT '',
	`date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (`id`)
);
